---
- name: Override reserved default security rules
  panos_default_security_rules:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    intrazone_profile_group: "{{ palo_alto_standalone_config_security_profile_group }}"
    intrazone_log_forwarding: "{{ palo_alto_standalone_config_log_forwarding_profile }}"
    interzone_action: drop
  when: not ansible_check_mode
