---
- name: Create PING interface management profile
  paloaltonetworks.panos.panos_management_profile:
    provider: "{{ current_firewall_provider }}"
    name: "{{ palo_alto_standalone_config_interface_management_profile }}"
    ping: true
    state: present

- name: Create zone protection profiles
  panos_rest_object:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    endpoint: Network/ZoneProtectionNetworkProfiles
    name: "{{ item }}"
    include_location: false
    create_with_name: true
    spec:
      flood:
        tcp-syn:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
        udp:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
        icmp:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "yes"
        icmpv6:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
        other-ip:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
      net-inspection:
        rule: {}
      discard-ip-spoof: "yes"
      discard-strict-source-routing: "yes"
      discard-security: "yes"
      discard-loose-source-routing: "yes"
      discard-stream-id: "yes"
      discard-timestamp: "yes"
      discard-unknown-option: "yes"
      discard-record-route: "yes"
      discard-malformed-option: "yes"
      discard-tcp-split-handshake: "yes"
      discard-overlapping-tcp-segment-mismatch: "yes"
      discard-icmp-ping-zero-id: "yes"
      discard-icmp-large-packet: "yes"
  loop:
    - "{{ palo_alto_standalone_config_internal_zone_protection_profile }}"
    - "{{ palo_alto_standalone_config_internet_zone_protection_profile }}"
  loop_control:
    label: "{{ item }}"

- name: Create LLDP profile
  panos_config_entry:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network/profiles/lldp-profile"
    name: "{{ palo_alto_standalone_config_lldp_profile }}"
    spec:
      option-tlvs:
        management-address:
          enabled: "no"
        port-description: "yes"
        system-name: "yes"
        system-description: "yes"
        system-capabilities: "yes"

- name: Enable global LLDP
  panos_rest_object:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    endpoint: Network/LLDP
    include_name: false
    include_location: false
    spec:
      enable: "yes"

- name: Apply zone protection profiles
  panos_config_entry:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone"
    name: "{{ item.name }}"
    spec:
      network:
        zone-protection-profile: "{{ item.profile }}"
  loop: "{{ palo_alto_standalone_config_zone_profile_assignments }}"
  loop_control:
    label: "{{ item.name }} -> {{ item.profile }}"

- name: Apply LLDP profile to non-internet interfaces
  panos_config_entry:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet"
    name: "{{ item.name }}"
    spec:
      layer3:
        lldp:
          enable: "yes"
          profile: "{{ palo_alto_standalone_config_lldp_profile }}"
  loop: "{{ palo_alto_standalone_config_internal_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
