---
- name: Create policy object tags
  ansible.builtin.include_tasks: object_tags.yml

- name: Create baseline address objects
  ansible.builtin.include_tasks: address_objects.yml

- name: Create baseline application objects
  ansible.builtin.include_tasks: application_objects.yml

- name: Create baseline security rules
  ansible.builtin.include_tasks: security_rules.yml

- name: Override reserved default security rules
  ansible.builtin.include_tasks: default_security_rules.yml
