---
- name: Create zone protection profiles
  panos_rest_object:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    endpoint: Network/ZoneProtectionNetworkProfiles
    name: "{{ item }}"
    include_location: false
    create_with_name: true
    spec:
      flood:
        tcp-syn:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
        udp:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
        icmp:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "yes"
        icmpv6:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
        other-ip:
          red:
            alarm-rate: 10000
            activate-rate: 10000
            maximal-rate: 40000
          enable: "no"
      net-inspection:
        rule: {}
      discard-ip-spoof: "yes"
      discard-strict-source-routing: "yes"
      discard-security: "yes"
      discard-loose-source-routing: "yes"
      discard-stream-id: "yes"
      discard-timestamp: "yes"
      discard-unknown-option: "yes"
      discard-record-route: "yes"
      discard-malformed-option: "yes"
      discard-tcp-split-handshake: "yes"
      discard-overlapping-tcp-segment-mismatch: "yes"
      discard-icmp-ping-zero-id: "yes"
      discard-icmp-large-packet: "yes"
  loop:
    - "{{ palo_alto_standalone_config_internal_zone_protection_profile }}"
    - "{{ palo_alto_standalone_config_internet_zone_protection_profile }}"
  loop_control:
    label: "{{ item }}"

- name: Create LLDP profile
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network/profiles/lldp-profile"
    element: |
      <entry name="{{ palo_alto_standalone_config_lldp_profile }}">
        <option-tlvs>
          <management-address>
            <enabled>no</enabled>
          </management-address>
          <port-description>yes</port-description>
          <system-name>yes</system-name>
          <system-description>yes</system-description>
          <system-capabilities>yes</system-capabilities>
        </option-tlvs>
      </entry>
    state: present

- name: Enable global LLDP
  panos_rest_object:
    ip_address: "{{ firewall_info.staging_ip }}"
    username: "{{ firewall_username }}"
    password: "{{ firewall_password }}"
    endpoint: Network/LLDP
    include_name: false
    include_location: false
    spec:
      enable: "yes"

- name: Apply zone protection profiles
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone"
    element: |
      <entry name="{{ item.name }}">
        <network>
          <zone-protection-profile>{{ item.profile }}</zone-protection-profile>
        </network>
      </entry>
    state: present
  loop: "{{ palo_alto_standalone_config_zone_profile_assignments }}"
  loop_control:
    label: "{{ item.name }} -> {{ item.profile }}"

- name: Apply LLDP profile to non-internet interfaces
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet"
    element: |
      <entry name="{{ item.name }}">
        <layer3>
          <lldp>
            <enable>yes</enable>
            <profile>{{ palo_alto_standalone_config_lldp_profile }}</profile>
          </lldp>
        </layer3>
      </entry>
    state: present
  loop: "{{ palo_alto_standalone_config_internal_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
