---
- name: Create zone protection profiles
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile"
    element: |
      <entry name="{{ item }}">
        <flood>
          <tcp-syn>
            <red>
              <alarm-rate>10000</alarm-rate>
              <activate-rate>10000</activate-rate>
              <maximal-rate>40000</maximal-rate>
            </red>
            <enable>no</enable>
          </tcp-syn>
          <udp>
            <red>
              <alarm-rate>10000</alarm-rate>
              <activate-rate>10000</activate-rate>
              <maximal-rate>40000</maximal-rate>
            </red>
            <enable>no</enable>
          </udp>
          <icmp>
            <red>
              <alarm-rate>10000</alarm-rate>
              <activate-rate>10000</activate-rate>
              <maximal-rate>40000</maximal-rate>
            </red>
            <enable>yes</enable>
          </icmp>
          <icmpv6>
            <red>
              <alarm-rate>10000</alarm-rate>
              <activate-rate>10000</activate-rate>
              <maximal-rate>40000</maximal-rate>
            </red>
            <enable>no</enable>
          </icmpv6>
          <other-ip>
            <red>
              <alarm-rate>10000</alarm-rate>
              <activate-rate>10000</activate-rate>
              <maximal-rate>40000</maximal-rate>
            </red>
            <enable>no</enable>
          </other-ip>
        </flood>
        <net-inspection>
          <rule/>
        </net-inspection>
        <discard-ip-spoof>yes</discard-ip-spoof>
        <discard-strict-source-routing>yes</discard-strict-source-routing>
        <discard-security>yes</discard-security>
        <discard-loose-source-routing>yes</discard-loose-source-routing>
        <discard-stream-id>yes</discard-stream-id>
        <discard-timestamp>yes</discard-timestamp>
        <discard-unknown-option>yes</discard-unknown-option>
        <discard-record-route>yes</discard-record-route>
        <discard-malformed-option>yes</discard-malformed-option>
        <discard-tcp-split-handshake>yes</discard-tcp-split-handshake>
        <discard-overlapping-tcp-segment-mismatch>yes</discard-overlapping-tcp-segment-mismatch>
        <discard-icmp-ping-zero-id>yes</discard-icmp-ping-zero-id>
        <discard-icmp-large-packet>yes</discard-icmp-large-packet>
      </entry>
    state: present
  loop:
    - "{{ palo_alto_standalone_config_internal_zone_protection_profile }}"
    - "{{ palo_alto_standalone_config_internet_zone_protection_profile }}"
  loop_control:
    label: "{{ item }}"

- name: Create LLDP profile
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network/profiles/lldp-profile"
    element: |
      <entry name="{{ palo_alto_standalone_config_lldp_profile }}">
        <option-tlvs>
          <management-address>
            <enabled>no</enabled>
          </management-address>
          <port-description>yes</port-description>
          <system-name>yes</system-name>
          <system-description>yes</system-description>
          <system-capabilities>yes</system-capabilities>
        </option-tlvs>
      </entry>
    state: present

- name: Enable global LLDP
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network"
    element: |
      <lldp>
        <enable>yes</enable>
      </lldp>
    state: present

- name: Apply zone protection profiles
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone"
    element: |
      <entry name="{{ item.name }}">
        <network>
          <zone-protection-profile>{{ item.profile }}</zone-protection-profile>
        </network>
      </entry>
    state: present
  loop: "{{ palo_alto_standalone_config_zone_profile_assignments }}"
  loop_control:
    label: "{{ item.name }} -> {{ item.profile }}"

- name: Apply LLDP profile to non-internet interfaces
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ current_firewall_provider }}"
    xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet"
    element: |
      <entry name="{{ item.name }}">
        <layer3>
          <lldp>
            <enable>yes</enable>
            <profile>{{ palo_alto_standalone_config_lldp_profile }}</profile>
          </lldp>
        </layer3>
      </entry>
    state: present
  loop: "{{ palo_alto_standalone_config_internal_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
