---
palo_alto_ha_default_netmask: 255.255.255.252
palo_alto_ha_primary_ha1_ip: 169.254.0.1
palo_alto_ha_secondary_ha1_ip: 169.254.0.2
palo_alto_ha_primary_priority: 90
palo_alto_ha_secondary_priority: 101
palo_alto_ha_preemptive: true
